# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://ikbase.net/"

theme = "congo"
defaultContentLanguage = "ja"

enableRobotsTXT = true
paginate = 10
summaryLength = 1

googleAnalytics = "G-LVJE5P7QPR"

timeout = "60s"


[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
blog = "/:section/:year/:month/:day/:filename/"